export const CATEGORIES = {
  "High-Ticket Clients": [
    "Dental Clinics",
    "Law Firms",
    "Real Estate Agencies",
    "Medical Practices",
    "Psychologists",
    "Accounting Firms",
    "Insurance Agencies",
    "Roofing Companies",
    "Plumbing Services",
    "HVAC Contractors",
    "Solar Energy Companies",
    "Gyms & Fitness Centers",
    "Luxury Spas",
    "Architecture Firms",
    "Construction Companies",
  ],
  "E-commerce & Retail": [
    "Online Stores",
    "Shopify Stores",
    "Dropshipping Businesses",
    "Clothing Brands",
    "Cosmetics Stores",
    "Electronics Retailers",
    "Home Decor Shops",
    "Jewelry Stores",
    "Gadget Stores",
    "Organic Food Stores",
  ],
  "Small Business Hub": [
    "Local Restaurants",
    "Coffee Shops",
    "Boutique Stores",
    "Pet Grooming",
    "Auto Repair Shops",
    "Bakery",
    "Florists",
    "Dry Cleaning",
    "Handyman Services",
    "Home Cleaning Services",
  ],
};

export const PLATFORMS = [
  "Google Maps",
  "Yelp",
  "LinkedIn",
  "Facebook",
  "Yellow Pages",
  "Angi",
  "Houzz",
];
