export const CATEGORIES = {
  "High-Value Contractors": [
    "Remodeling contractors",
    "Civil contractors",
    "Structural contractors",
    "Concrete contractors",
    "Electrical contractors",
    "HVAC contractors",
    "Painting contractors",
    "General Contractors",
    "Subcontractors",
    "Roofing Contractors",
    "Plumbing Contractors",
    "Demolition Contractors",
    "Masonry Contractors",
    "Excavation Companies",
    "Steel Fabricators",
  ],
  "Design & Architecture": [
    "Architectural design firms",
    "Residential architects",
    "Commercial architects",
    "CAD drafting services",
    "Architectural drafting services",
    "2D & 3D rendering services",
    "Permit expediting services",
    "Building design services",
    "Plan holders (construction bidding)",
    "Structural Engineers",
    "Civil Engineers",
    "Mechanical Engineers",
    "Electrical Engineers",
    "Interior Designers",
    "Landscape Architects",
    "BIM Modeling Companies",
  ],
};

export const PLATFORMS = [
  "Google Maps",
  "Yelp",
  "LinkedIn",
  "Facebook",
  "Yellow Pages",
  "Angi",
  "Houzz",
];
